from celular_bateria import Bateria, Celular

# Criando as 3 instâncias Celular
print("Criando celular 1:")
celular1 = Celular(1321677)
print("Criando celular 2:")
celular2 = Celular(1321655)
print("Criando celular 3:")
celular3 = Celular(1321688)

# Testando todos os métodos
print("\nCelular 1:")
print(celular1)
celular1.ligardesligar()
celular1.assistir_video(10)
celular1.carregar(50)
celular1.ligar_desligar_wifi()
celular1.assistir_video(10)
celular1.descarregar(30)
celular1.ligardesligar()
celular1.retirar_bateria()
celular1.colocar_bateria(Bateria(7000))  

print("\nCelular 2:")
print(celular2)
celular2.ligardesligar()
celular2.assistir_video(20)
celular2.carregar(30)
celular2.ligar_desligar_wifi()
celular2.assistir_video(5)
celular2.descarregar(10)
celular2.ligardesligar()
celular2.retirar_bateria()
celular2.colocar_bateria(Bateria(5555)) 

print("\nCelular 3:")
print(celular3)
celular3.ligardesligar()
celular3.assistir_video(15)
celular3.carregar(20)
celular3.ligar_desligar_wifi()
celular3.assistir_video(7)
celular3.descarregar(20)
celular3.ligardesligar()
celular3.retirar_bateria()
celular3.colocar_bateria(Bateria(6523)) 
