teste = open('teste.py', 'r')
print(teste.read())
teste.close()
teste = open('teste.py', 'a+')
print(teste.read())
conteudo = input("Digite o nome:")
teste.write(conteudo)
teste.write('\n')
teste.close()
teste = open('teste.py', 'r')
print(teste.read())
teste.close()